<?php

declare(strict_types=1);

namespace Renrhaf\SyliusBrevoPlugin\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

final class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('renrhaf_sylius_brevo');
        $rootNode = $treeBuilder->getRootNode();

        $rootNode
            ->children()
                ->arrayNode('api')
                    ->isRequired()
                    ->children()
                        ->scalarNode('key')
                            ->isRequired()
                            ->cannotBeEmpty()
                            ->info('Brevo API key')
                        ->end()
                        ->scalarNode('client_key')
                            ->defaultNull()
                            ->info('Brevo client key for frontend tracking scripts')
                        ->end()
                    ->end()
                ->end()

                ->arrayNode('webhook')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('secret')
                            ->defaultNull()
                            ->info('Secret token for webhook authentication')
                        ->end()
                        ->booleanNode('enabled')
                            ->defaultTrue()
                        ->end()
                        ->integerNode('log_retention_days')
                            ->defaultValue(90)
                            ->min(1)
                        ->end()
                    ->end()
                ->end()

                ->arrayNode('newsletter')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultTrue()
                        ->end()
                        ->integerNode('list_id')
                            ->isRequired()
                            ->info('Brevo newsletter list ID')
                        ->end()
                        ->booleanNode('double_opt_in')
                            ->defaultFalse()
                        ->end()
                        ->integerNode('doi_template_id')
                            ->defaultNull()
                            ->info('Brevo DOI email template ID (required if double_opt_in is true)')
                        ->end()
                        ->scalarNode('doi_redirect_url')
                            ->defaultNull()
                            ->info('URL to redirect after DOI confirmation')
                        ->end()
                        ->booleanNode('checkout_subscribe')
                            ->defaultFalse()
                            ->info('Show newsletter opt-in checkbox at checkout')
                        ->end()
                    ->end()
                ->end()

                ->arrayNode('contacts')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultTrue()
                        ->end()
                        ->booleanNode('sync_on_create')
                            ->defaultTrue()
                        ->end()
                        ->booleanNode('sync_on_update')
                            ->defaultTrue()
                        ->end()
                        ->integerNode('batch_size')
                            ->defaultValue(100)
                            ->min(1)
                            ->max(500)
                        ->end()
                        ->arrayNode('attribute_mapping')
                            ->useAttributeAsKey('sylius_field')
                            ->scalarPrototype()->end()
                            ->defaultValue([
                                'firstName' => 'PRENOM',
                                'lastName' => 'NOM',
                                'phoneNumber' => 'SMS',
                            ])
                        ->end()
                    ->end()
                ->end()

                ->arrayNode('ecommerce')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultTrue()
                        ->end()
                        ->arrayNode('products')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('sync_enabled')
                                    ->defaultTrue()
                                ->end()
                                ->integerNode('batch_size')
                                    ->defaultValue(100)
                                    ->min(1)
                                    ->max(100)
                                ->end()
                                ->scalarNode('brand_attribute')
                                    ->defaultNull()
                                    ->info('Sylius product attribute code to use as Brevo brand (e.g. "brand"). Leave null to skip.')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('orders')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('sync_enabled')
                                    ->defaultTrue()
                                ->end()
                                ->arrayNode('sync_statuses')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['new', 'completed', 'shipped', 'cancelled', 'refunded'])
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('categories')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('sync_enabled')
                                    ->defaultTrue()
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('cart_tracking')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')
                                    ->defaultTrue()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()

                ->arrayNode('tracker')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultTrue()
                        ->end()
                    ->end()
                ->end()

                ->arrayNode('chat')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultFalse()
                        ->end()
                        ->scalarNode('widget_id')
                            ->defaultNull()
                            ->info('Brevo Conversations widget ID')
                        ->end()
                    ->end()
                ->end()

                ->arrayNode('transactional_email')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultFalse()
                        ->end()
                        ->arrayNode('sender')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('name')
                                    ->defaultNull()
                                    ->info('Sender name for transactional emails')
                                ->end()
                                ->scalarNode('email')
                                    ->defaultNull()
                                    ->info('Sender email address')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('templates')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->integerNode('order_confirmation')
                                    ->defaultNull()
                                    ->info('Brevo template ID for order confirmation')
                                ->end()
                                ->integerNode('order_shipped')
                                    ->defaultNull()
                                    ->info('Brevo template ID for order shipped')
                                ->end()
                                ->integerNode('customer_welcome')
                                    ->defaultNull()
                                    ->info('Brevo template ID for new customer welcome')
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()

                ->arrayNode('sms')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultFalse()
                        ->end()
                        ->scalarNode('sender')
                            ->defaultNull()
                            ->info('SMS sender name (max 11 alphanumeric chars)')
                        ->end()
                        ->arrayNode('events')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->arrayNode('order_confirmation')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->booleanNode('enabled')
                                            ->defaultFalse()
                                        ->end()
                                        ->scalarNode('content')
                                            ->defaultValue('Your order {ORDER_NUMBER} has been confirmed. Total: {ORDER_TOTAL}.')
                                        ->end()
                                    ->end()
                                ->end()
                                ->arrayNode('order_shipped')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->booleanNode('enabled')
                                            ->defaultFalse()
                                        ->end()
                                        ->scalarNode('content')
                                            ->defaultValue('Your order {ORDER_NUMBER} has been shipped!')
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
